version: '3.6'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elastic01
    environment:
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic

  fluentd:
    build: ./fluentd
    container_name: fluentd01
    links:
       - "elasticsearch"
    ports:
      - 24224:24224
      - "24224:24224/udp"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana01
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/cert:/usr/share/kibana/config/cert
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge

  # elasticsearch: http://172.18.0.2:9200/*/_search?pretty=true&q=*:*
