#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab03_1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 03.
# Description:       Configures GPIO for Lab 03.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio36/direction
	echo -n "0" > /sys/class/gpio/gpio36/value

	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio6/direction
	echo -n "falling" > /sys/class/gpio/gpio6/edge
	chgrp gpio /sys/class/gpio/gpio6/value
	chgrp gpio /sys/class/gpio/gpio6/edge
	chmod g+rw /sys/class/gpio/gpio6/value
	chmod g+rw /sys/class/gpio/gpio6/edge
	;;
    stop)
    	echo -n "in" > /sys/class/gpio/gpio6/direction
    	echo -n "6" > /sys/class/gpio/unexport
    	echo -n "1" > /sys/class/gpio/gpio36/value
	echo -n "36" > /sys/class/gpio/unexport
	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
