#! /bin/sh
### BEGIN INIT INFO
# Provides:          initLab7_1
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 7.
# Description:       Configures GPIO for Lab 7.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

        # ADC_A0 as one-shot ADC in

        # Linux: in_voltage0_raw
        chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
        chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
        chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
        chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale

        # Resistor: gpio49 disabled
        if [! -d /sys/class/gpio/gpio49 ] ; then
            echo -n "49" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio49/direction
    	;;
    stop)
        echo -n "49" > /sys/class/gpio/unexport
        ;;
    status)
    	ls -d /sys/class/gpio/gpio*
        ;;
    *)
    	echo -n "Usage: $0 "
    	echo "{start|stop|restart|force-reload|status}"
    	exit 1
    	;;
esac

exit 0
