#! /bin/sh
### BEGIN INIT INFO
# Provides:          initLab03_blinkButton
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 03.
# Description:       Configures GPIO for Lab 03.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

        # IO 02 as digital in -------------------------------------------------------

        # Linux: gpio13 = in
        if [ ! -d /sys/class/gpio/gpio13 ] ; then
            echo -n "13" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio13/direction
        chgrp gpio /sys/class/gpio/gpio13/value
        chmod g+rw /sys/class/gpio/gpio13/value

        # Level Shifter: gpio34 = 1 = in
        if [ ! -d /sys/class/gpio/gpio34 ] ; then
            echo "34" > /sys/class/gpio/export
        fi
        echo "1" > /sys/class/gpio/gpio34/value
        echo "in" > /sys/class/gpio/gpio34/direction

        # Resistor: gpio35 = pull-down = 0
        if [ ! -d /sys/class/gpio/gpio35 ] ; then
            echo "35" > /sys/class/gpio/export
        fi
        echo "0" > /sys/class/gpio/gpio35

        # Mux 1: gpio77 = 0
        if [ ! -d /sys/class/gpio/gpio77 ] ; then
            echo "77" > /sys/class/gpio/export
        fi
        echo "0" > /sys/class/gpio/gpio77/value

        # IO 03 as digital out ------------------------------------------------------

        # Linux: gpio62 = out
        if [ ! -d /sys/class/gpio/gpio62 ] ; then
            echo -n "62" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio62/direction
        chgrp gpio /sys/class/gpio/gpio62/value
        chmod g+rw /sys/class/gpio/gpio62/value

        # Level Shifter: NA

        # Resistor: NA

        # Mux 1: gpio76 = low = 0
        if [ ! -d /sys/class/gpio/gpio76 ] ; then
            echo "76" > /sys/class/gpio/export
        fi
        echo "0" > /sys/class/gpio/gpio76/value

        # Mux 2: gpio64 = low = 0
        if [ ! -d /sys/class/gpio/gpio64 ] ; then
            echo "64" > /sys/class/gpio/export
        fi
        echo "0" > /sys/class/gpio/gpio64/value
        echo "out" > /sys/class/gpio64/direction
    	;;
    stop)
        echo -n "64" > /sys/class/gpio/unexport
        echo -n "76" > /sys/class/gpio/unexport
        echo -n "62" > /sys/class/gpio/unexport
        echo -n "13" > /sys/class/gpio/unexport
        echo -n "34" > /sys/class/gpio/unexport
        echo -n "35" > /sys/class/gpio/unexport
        echo -n "77" > /sys/class/gpio/unexport
        ;;
    status)
    	ls -d /sys/class/gpio/gpio*
        ;;
    *)
    	echo -n "Usage: $0 "
    	echo "{start|stop|restart|force-reload|status}"
    	exit 1
    	;;
esac

exit 0
