all:
	make -C ./lib
	make -C ./rec
	make -C ./trans

clean:
	make clean -C ./rec
	make clean -C ./trans
	make clean -C ./lib

distclean:
	make distclean -C ./rec
	make distclean -C ./trans
	make distclean -C ./lib
