#! /bin/sh
### BEGIN INIT INFO
# Provides:          Prova2
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

case "$1" in
    start|restart|force-reload)

##########TRANSMISSOR###########

#IO5 = DATA

        # Linux: gpio0
        if [ ! -d /sys/class/gpio/gpio0 ] ; then
            echo -n "0" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio0/direction
        chgrp gpio /sys/class/gpio/gpio0/value
        chmod g+rw /sys/class/gpio/gpio0/value

        # Level shifter: gpio18
        if [ ! -d /sys/class/gpio/gpio18 ] ; then
            echo -n "18" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio18/direction
        echo -n "1" > /sys/class/gpio/gpio18/value

        # Resistor: gpio19
        if [ ! -d /sys/class/gpio/gpio19 ] ; then
            echo -n "19" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio19/direction
        echo -n "0" > /sys/class/gpio/gpio19/value

        # Pin Mux 1: gpio66 (low)
        if [ ! -d /sys/class/gpio/gpio66 ] ; then
            echo -n "66" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio66/value
        echo -n "out" > /sys/class/gpio/gpio66/direction

#IO6 = ACK

        # Linux: gpio1
        if [ ! -d /sys/class/gpio/gpio1 ] ; then
            echo -n "1" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio1/direction
        chgrp gpio /sys/class/gpio/gpio1/value
        chmod g+rw /sys/class/gpio/gpio1/value
        chgrp gpio /sys/class/gpio/gpio1/edge
	      chmod g+rw /sys/class/gpio/gpio1/edge

        # Level shifter: gpio20
        if [ ! -d /sys/class/gpio/gpio20 ] ; then
            echo -n "20" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio20/direction
        echo -n "1" > /sys/class/gpio/gpio20/value

        # Resistor: gpio21
        if [ ! -d /sys/class/gpio/gpio21 ] ; then
            echo -n "21" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio21/direction
        echo -n "0" > /sys/class/gpio/gpio21/value

        # Pin Mux 1: gpio68 (low)
        if [ ! -d /sys/class/gpio/gpio68 ] ; then
            echo -n "68" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio68/value
        echo -n "out" > /sys/class/gpio/gpio68/direction

#IO7 = CLK

        # Linux: gpio38
        if [ ! -d /sys/class/gpio/gpio38 ] ; then
            echo -n "38" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio38/direction
        chgrp gpio /sys/class/gpio/gpio38/value
        chmod g+rw /sys/class/gpio/gpio38/value
        chgrp gpio /sys/class/gpio/gpio38/edge
        chmod g+rw /sys/class/gpio/gpio38/edge

        # Resistor: gpio39
        if [ ! -d /sys/class/gpio/gpio39 ] ; then
            echo -n "39" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio39/direction

##########RECEPTOR##########

#IO4 = DATA

        # Linux: gpio6
        if [ ! -d /sys/class/gpio/gpio6 ] ; then
            echo -n "6" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio6/direction
        chgrp gpio /sys/class/gpio/gpio6/value
        chmod g+rw /sys/class/gpio/gpio6/value

        # Level shifter: gpio36
        if [ ! -d /sys/class/gpio/gpio36 ] ; then
            echo -n "36" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio36/direction
        echo -n "1" > /sys/class/gpio/gpio36/value

        # Resistor: gpio37
        if [ ! -d /sys/class/gpio/gpio37 ] ; then
            echo -n "37" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio37/direction
        echo -n "0" > /sys/class/gpio/gpio37/value


#IO3 = ACK

        # Linux: gpio14
        if [ ! -d /sys/class/gpio/gpio14 ] ; then
            echo -n "14" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio14/direction
        chgrp gpio /sys/class/gpio/gpio14/value
        chmod g+rw /sys/class/gpio/gpio14/value
        chgrp gpio /sys/class/gpio/gpio14/edge
	      chmod g+rw /sys/class/gpio/gpio14/edge

        # Level shifter: gpio16
        if [ ! -d /sys/class/gpio/gpio16 ] ; then
            echo -n "16" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio16/direction
        echo -n "1" > /sys/class/gpio/gpio16/value

        # Resistor: gpio17
        if [ ! -d /sys/class/gpio/gpio17 ] ; then
            echo -n "17" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio17/direction
        echo -n "0" > /sys/class/gpio/gpio17/value

        # Pin Mux 1: gpio76 (low)
        if [ ! -d /sys/class/gpio/gpio76 ] ; then
            echo -n "76" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio76/value
        echo -n "out" > /sys/class/gpio/gpio76/direction

        # Pin Mux 2: gpio64 (low)
        if [ ! -d /sys/class/gpio/gpio64 ] ; then
            echo -n "64" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio64/value
        echo -n "out" > /sys/class/gpio/gpio64/direction

#IO2 = CLK

        # Linux: gpio13
        if [ ! -d /sys/class/gpio/gpio13 ] ; then
            echo -n "13" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio13/direction
        chgrp gpio /sys/class/gpio/gpio13/value
        chmod g+rw /sys/class/gpio/gpio13/value
        chgrp gpio /sys/class/gpio/gpio13/edge
        chmod g+rw /sys/class/gpio/gpio13/edge

        # Level shifter: gpio34
        if [ ! -d /sys/class/gpio/gpio34 ] ; then
            echo -n "34" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio34/direction
        echo -n "1" > /sys/class/gpio/gpio34/value

        # Resistor: gpio35
        if [ ! -d /sys/class/gpio/gpio35 ] ; then
            echo -n "35" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio35/direction

        # Pin Mux 1: gpio77 (low)
        if [ ! -d /sys/class/gpio/gpio77 ] ; then
            echo -n "77" > /sys/class/gpio/export
        fi
        echo -n "0" > /sys/class/gpio/gpio77/value
        echo -n "out" > /sys/class/gpio/gpio77/direction

        chgrp i2c /dev/i2c-0
        chmod g+rw /dev/i2c-0

    	;;
    stop)


        # IO 00
        echo -n "11" > /sys/class/gpio/unexport
        echo -n "32" > /sys/class/gpio/unexport
        echo -n "33" > /sys/class/gpio/unexport
        # IO 01
        echo -n "12" > /sys/class/gpio/unexport
        echo -n "28" > /sys/class/gpio/unexport
        echo -n "29" > /sys/class/gpio/unexport
        echo -n "45" > /sys/class/gpio/unexport
        # IO 08
        echo -n "40" > /sys/class/gpio/unexport
        echo -n "41" > /sys/class/gpio/unexport
        # IO 09
        echo -n "22" > /sys/class/gpio/unexport
        echo -n "23" > /sys/class/gpio/unexport
        echo -n "70" > /sys/class/gpio/unexport
        # IO 10
        echo -n "26" > /sys/class/gpio/unexport
        echo -n "27" > /sys/class/gpio/unexport
        echo -n "74" > /sys/class/gpio/unexport
        # IO 11
        echo -n "24" > /sys/class/gpio/unexport
        echo -n "25" > /sys/class/gpio/unexport
        echo -n "44" > /sys/class/gpio/unexport
        echo -n "72" > /sys/class/gpio/unexport
        # IO 12
        echo -n "42" > /sys/class/gpio/unexport
        echo -n "43" > /sys/class/gpio/unexport
        # IO 13
        echo -n "30" > /sys/class/gpio/unexport
        echo -n "31" > /sys/class/gpio/unexport
        echo -n "46" > /sys/class/gpio/unexport
        ;;
    status)
    	ls -d /sys/class/gpio/gpio*
        ;;
    *)
    	echo -n "Usage: $0 "
    	echo "{start|stop|restart|force-reload|status}"
    	exit 1
    	;;
esac

exit 0
